name: gaussian_splatting
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:

  - python=3.12
  - cuda-toolkit=12.4
  # cuda-toolkit版本在https://anaconda.org/search?q=cuda-toolkit+ 查询，需要跟CUDA版本一致
  - pytorch-cuda=12.4
  # pytorch-cuda版本 https://pytorch.org/get-started/locally/ 查询，需要跟CUDA版本一致
  - vs2022_win-64
  # vs2022_win-64 vs版一致
  - plyfile
  - pip
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
